# TASK 1
dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [3]:
import pandas as pd

df = pd.read_csv('vgsalesGlobale.csv')

In [4]:
#total global sales
totalglobalsales = df['Global_Sales'].sum()
print("Total Global Sales:", totalglobalsales)

Total Global Sales: 8920.44


In [5]:
#game with the highest global sales
highestsalesgame = df.loc[df['Global_Sales'].idxmax(), 'Name']
print("Game with Highest Global Sales:", highestsalesgame)

Game with Highest Global Sales: Wii Sports


In [6]:
#average sales for each region
averagesalesperregion = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average Sales per Region:\n", averagesalesperregion)


Average Sales per Region:
 NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [7]:
#top 5 most popular game genres based on global sales
topgenres = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 Most Popular Game Genres:\n", topgenres)

Top 5 Most Popular Game Genres:
 Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [8]:
#total sales for each genre in each region
genresalesbyregion = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
#most popular genre in north america
mostpopulargenreNA = genresalesbyregion['NA_Sales'].idxmax()
print("Most Popular Genre in North America:", mostpopulargenreNA)

In [10]:
print("Last 10 Rows:\n", df.tail(10))

Last 10 Rows:
         Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   


In [11]:
#top 3 gaming platforms with the highest global sales
topplatforms = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("Top 3 Gaming Platforms:\n", topplatforms)


Top 3 Gaming Platforms:
 Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [12]:
#calculating the market share for each genre
totalsalesbygenre = df.groupby('Genre')['Global_Sales'].sum()
genre_market_share = (totalsalesbygenre / totalglobalsales) * 100
print("Market Share by Genre (%):\n", genre_market_share)


Market Share by Genre (%):
 Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [13]:
#calculating the correlation coefficient between NA and EU
correlation = df['NA_Sales'].corr(df['EU_Sales'])
print("Correlation Coefficient between NA_Sales and EU_Sales:", correlation)

Correlation Coefficient between NA_Sales and EU_Sales: 0.767726748370264


## Task 2 English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [14]:
english_to_spanish = {
    "hello": "hola",
    "goodbye": "adiós",
    "please": "por favor",
    "thank you": "gracias",
    "yes": "sí",
    "no": "no",
    "morning": "mañana",
    "night": "noche",
    "water": "agua",
    "food": "comida"
}

while True:
    word = input("Enter an English word or enter 'q' to quit: ").strip().lower()
    
    if word == "q":
        break
    
    translation = english_to_spanish.get(word)
    if translation:
        print(f"The Spanish translation of '{word}' is '{translation}'.")
    else:
        print("Translation not available.")


The Spanish translation of 'no' is 'no'.
Translation not available.
Goodbye!



## Task 3 Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [19]:
def classify_emails(emails):
    importantkeywords = {"meeting", "project", "deadline", "urgent", "client"}
    promotionkeywords = {"sale", "discount", "offer", "deal", "promo"}
    spamkeywords = {"win", "prize", "lottery", "free money", "click here"}
    
    important_emails = []
    promotion_emails = []
    spam_emails = []
    
    for email in emails:
        email_lower = email.lower()
        if any(keyword in email_lower for keyword in importantkeywords):
            important_emails.append(email)
        elif any(keyword in email_lower for keyword in promotionkeywords):
            promotion_emails.append(email)
        elif any(keyword in email_lower for keyword in spamkeywords):
            spam_emails.append(email)
        else:
            important_emails.append(email)  
    
    return important_emails, promotion_emails, spam_emails


emails = [
    "Meeting scheduled for tomorrow",
    "Huge discount on all items!",
    "You just won a prize of $30000",
    "Congratulations! You won a prize!",
    "Project deadline extended",
    "We have an urgert meeting tomorrow",
    "Exclusive offer just for you"
]

important, promotions, spam = classify_emails(emails)

print("Important Emails:")
print(important)
print("Promotion Emails:")
print(promotions)
print("Spam Emails:")
print(spam)


Important Emails:
['Meeting scheduled for tomorrow', 'Project deadline extended', 'We have an urgert meeting tomorrow']
Promotion Emails:
['Huge discount on all items!', 'Exclusive offer just for you']
Spam Emails:
['You just won a prize of $30000', 'Congratulations! You won a prize!']


## Task 4 Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

In [22]:
shoppingcart = []
products = {
    1: "Samsung",
    2: "Apple",
    3: "Mi",
    4: "Pixel",
    5: "Huawei"
}

print("Welcome to the Online Store!")
print("Available Products:")
for key, value in products.items():
    print(f"{key}: {value}")

while True:
    choice = input("Enter the number of the product to add to cart (or 'q' to quit): ").strip().lower()
    
    if choice == 'q':
        break
    
    if choice.isdigit():
        choice = int(choice)
        if choice in products:
            shoppingcart.append(products[choice])
            print(f"{products[choice]} has been added to cart.")
        else:
            print("Invalid choice. Please enter a number between 1 and 5.")
    else:
        print("Invalid input. Please enter a valid number or 'q' to quit.")

print("\nYour Shopping Cart:")
for item in shoppingcart:
    print(f"- {item}")

print("Thank you for shopping")


Welcome to the Online Store!
Available Products:
1: Samsung
2: Apple
3: Mi
4: Pixel
5: Huawei
Apple has been added to cart.
Pixel has been added to cart.

Your Shopping Cart:
- Apple
- Pixel
Thank you for shopping


## Task 5
* Create two NumPy arrays of the same shape and perform element-wise addition on them.
* Calculate the element-wise product of two NumPy arrays.

In [23]:
import numpy as np

a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

sum_array = a1 + a2
product_array = a1 * a2

print("Element-wise Addition:", sum_array)
print("Element-wise Product:", product_array)

Element-wise Addition: [ 7  9 11 13 15]
Element-wise Product: [ 6 14 24 36 50]


## Task 6
* Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

* Concatenate two NumPy arrays horizontally and vertically.

In [29]:
a1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a2d = a1d.reshape(3, 4)
print("Reshaped 2D Array:\n", a2d)

#used arrays from previous question
horizontal_concat = np.hstack((a1.reshape(-1, 1), a2.reshape(-1, 1)))
vertical_concat = np.vstack((a1, a2))

print("Horizontally Concatenated Array:\n", horizontal_concat)
print("Vertically Concatenated Array:\n", vertical_concat)


Reshaped 2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Horizontally Concatenated Array:
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
Vertically Concatenated Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Task 7
* Reverse A List In Python Using Slicing


In [30]:
rlist = a1[::-1]
print(rlist)

[5 4 3 2 1]


# TASK 8
You need to download the GitHub Desktop software, push your lab task to your GitHub account, and share the link on GCR as a submission.